// <auto-generated />
namespace E_biblioteka.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Requiredfieldsannotated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Requiredfieldsannotated));
        
        string IMigrationMetadata.Id
        {
            get { return "201908241857091_Required fields annotated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
